### ISSUE TITLE
One issue for assignment 2

### ISSUE THREAD

**Issue by jind11** [akaitsuki-ii/CS224n#1]
For the parse_step function in the file q2_parser_transitions.py of assignment 2, my code is pretty similar to yours but I came across one issue, that is, the left and right arc should have preconditions to be executed. Say, left and right arc cannot be executed if there are less than 2 items in the stack. When I run the file q2_parser_model.py, I got the error that when the stack has only "ROOT" item, the prediction of next transition is wrongly left arc, then the stack cannot the unpacked out 2 item, which brought out an error. I don't know how to solve this problem. Could you check it and provide some ideas? Thanks!

**Comment by akaitsuki-ii** [comment]
Hi, Di Jin. I did think about the problem when writing the code, but it seems never crash...

If you check the function `create_instances` in *parser_utils.py*, you will find that the model is trained with *instances* (not raw *PartialParse*), which is splited into individual gold parsing step. And there is not any transition operation during training time, and we will not meet the problem. What's more, after the model is well-trained on the data, we can suppose that the model *should not* give wrong, illegal prediction (such as "left-arc" transtion on an empty stack like you mentioned above). I think this is why my model never crash...

However, if your model still crashes because of giving illegal prediction during testing time. I have an idea that you can let *legal_labels* (please check `legal_labels` in *parser_utils.py*) a part of input argument of your model (I mean add one more *tf.placeholder*), make it a mask of the output (may be `pred * mask`), and then the model should not give illegal prediction.

**Comment by jind11** [comment]
Thanks for your feedback! When the model is being trained, it is evaluated by running it through the PartialParse and fortunately, even when the loss is still high at the beginning of the training process, the mistake that I mentioned has never been come across. I don't know whether it is always the case or it is just because of good luck. Anyway, thanks for the comments and I have solved this problem.
